definition:
  description: Permission Table
  name: permission
  plural: permissions
  type: persisted
properties: 
  name:
    type: string
    required: true
  role: 
    type: string
    required: true