definition:
  description: User Table
  name: user
  plural: users
  type: persisted
properties: 
  email:
    type: string
    required: true
  name:
    type: string
    required: true
  password: 
    hidden: true
    type: string
    required: true
  verified:
    type: boolean
    required: true
    default: false
  token: 
    hidden: true
    type: string
    required: false
    default: null
relations: 
  restaurants:
    model: permission
    type: hasMany
    options: 
      as: permissions
routes:
  -
    route: /count
    method: count
    handler: get
    permission: authenticated
  - 
    route: /:id
    method: findById
    handler: get
    permission: authenticated