definition:
  description: Restaurant Table
  name: restaurant
  plural: restaurants
  type: persisted
properties: 
  name:
    type: string
    required: true
  place: 
    type: string
    required: true
  typeOfFood: 
    type: string
    required: true
relations: 
  users:
    model: User
    type: hasMany
    options: 
      as: users
