definition:
  description: User Table
  name: user
  plural: users
  type: persisted
properties: 
  lastName:
    type: string
    required: true
  name: 
    type: string
    length: 11
    required: true
relations: 
  restaurants:
    model: Restaurant
    type: belongsTo
    options: 
      as: restaurant