definition:
  description: User Table
  name: user
  plural: users
  type: persisted
properties: 
  email:
    type: string
    required: true
  name:
    type: string
    required: true
  password: 
    type: string
    required: true
  verified:
    type: boolean
    required: true
    default: false
  token: 
    type: string
    required: false
    default: null
relations: 
  restaurants:
    model: permission
    type: hasMany
    options: 
      as: permissions